### PR TITLE
3 new design jobs

### PR DESCRIPTION
**Pull request by fuselagetown**
I've added three pages in the jobs folder, and listed them on the jobs page.

### CODE REVIEW

**Comment by fuselagetown** [comment]
@davetron5000 @elbeld I've included the partial _design_perks at the bottom, and put a link to the application form at the top and bottom.

**Comment by davetron5000** [comment]
I don't see the design perks file.  Did you forget to add it?

**Comment by fuselagetown** [comment]
It's a partial in /includes, which was in there already. I just included it in the jobs files.

- Torunn

**Comment by davetron5000** [comment]
Ah, ok, didn't see that. I say merge when ready! :+1:

**Pull request merged**
