### PR TITLE
New Layout

### PR DESCRIPTION
**Pull request by leobalter**
in order to finish there are some small tasks to assure this PR is ok:

- [ ] verify team members pics on the Engineering and Algorithms pages
- [ ] clear out the example post on `engineering/_posts/` using a categorized post with a team member data.
- [ ] fill the job locations with real data, the current data is just used as example. The files are located at `_jobs/*.md`.

### CODE REVIEW

**Comment by davetron5000** [comment]
@leobalter are you looking for comments/feedback, or is this just a step toward launch?

**Comment by leobalter** [comment]
this is just a step forward launch, but comments and feedback would be helpful.

**Comment by davetron5000** [comment]
This doesn't incorporate any of the changes based on my latest round of feedback.  Should I re-post here, or would you prefer email?

Also, are these the final “hero” images?  They load very slowly when I'm running locally

**Comment by aaronsbrown** [comment]
@davetron5000 

Just FYI, our contract with Bocoup is up, so they won't be making any more changes. We'll be doing them in-house when Eli is back.

These aren't the final hero images, just placeholders. I'm guessing these images are full-res, unoptimized. 

Can you add your latest round of feedback here just to capture it (i never saw it).

Thanks,
Aaron

**Comment by davetron5000** [comment]
OK, good to know.  We should probably take this offline, as this repo is public.

I'll start an email chain.

**Comment by davetron5000** [comment]
I've copied this over to a private repo so we can discuss in GH, but not in public.

**Comment by davetron5000** [comment]
Closing this as we have the code in another repo as we get ready for go-live

**Comment by ndp** [comment]
Hi, are new people supposed to add themselves to a different repo? If so,
which one?

**Comment by davetron5000** [comment]
I'll email eng with the deets

**Pull request closed without merging**
