### PR TITLE
Add Nicola to teampage

### PR DESCRIPTION
**Pull request by nicolaa**

### CODE REVIEW

**Comment by davidamcclain** [comment]
Great to have you here, Nicola. Where is that photo from?

**Comment by davetron5000** [comment]
woot!

**Comment by jonathandean** [comment]
awesome! excited to have you :)

**Comment by nickflux** [comment]
Welcome :+1:

**Comment by pdudek** [comment]
Very cool pic! Glad to have you :tada:

**Comment by jstrait** [comment]
Welcome!

**Comment by nicolaa** [comment]
Thanks guys! Great to be here! This was taken in Peru (on the Inca trail).

**Comment by emmafern** [comment]
Welcome!

**Pull request merged**
