### PR TITLE
guidelines for open-source repos

### PR DESCRIPTION
**Pull request by davetron5000**
Ping @simeonwillbanks @yorthehunter @codevelvet @webdestroya and whoever else I'm forgetting (I guess we need a GitHub group?)

It's not the most aesthetically pleasing:

stitch_fix_technology

### CODE REVIEW

**Comment by codevelvet** [comment]
That or we could link to a `CONTRIBUTING.md.example` and a [live version](https://github.com/stitchfix/immutable-struct/blob/master/CONTRIBUTING.md)

**Comment by davetron5000** [comment]
@codevelvet Do you think would work better than showing it inline?  I was going for a "copy and paste" thing, but it's pretty darn verbose now so maybe links would be better instead?

**Comment by codevelvet** [comment]
I think the link would be nice so that people can just download the example file.  Then you don't have to worry about copy/pasting into the html, although it shouldn't change that often.

**Comment by simeonwillbanks** [comment]
@davetron5000 Thanks these guidelines!  Please, may we add the [README template](https://gist.github.com/simeonwillbanks/ce43ed27376cd6f51ebb) created by @ndp and myself?

**Comment by davetron5000** [comment]
@simeonwillbanks @codevelvet check now.  Created `/templates` that has `.txt` versions of some artifacts (`.txt` so jekyll doesn't render them as HTML).

**Comment by davetron5000** [comment]
stitch_fix_technology

**Comment by codevelvet** [comment]
:+1:

**Pull request merged**
